from alpine:edge

# Build setup
ADD setup-build-env.sh /bin/setup-build-env.sh
RUN setup-build-env.sh
ADD build.sh /bin/build.sh
USER packager
WORKDIR /home/packager

# Build nightly Oils
# Comment out for latest alpine build
ADD install-dirty-oils.sh install-dirty-oils.sh
RUN ./install-dirt-oils.sh

VOLUME ["/home/packager/.abuild"]
VOLUME ["/home/packager/aports"]
VOLUME ["/home/packager/packages"]
ENTRYPOINT ["/bin/build.sh"]
